# Site Settings
title: Lucas Czajka
description: A brief description of your site.
baseurl: "" # Leave this empty if deploying to root of a domain, otherwise use "/your-repo-name"
url: "https://your-username.github.io" # Your website URL (GitHub Pages URL or custom domain)

# Author
author:
  name: Your Name
  email: your-email@example.com

# Build Settings
theme: minima # Using the default Minima theme
markdown: kramdown

# Defaults for your posts
defaults:
  - scope:
      path: "" # Applies to all files
      type: posts
    values:
      layout: post
      author: Your Name

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Enable GitHub Pages plugin
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social Media Links (Optional)
social_links:
  twitter: https://twitter.com/yourusername
  github: https://github.com/yourusername
  linkedin: https://linkedin.com/in/yourusername

# Configuration for SEO Tag Plugin
seo:
  title: Your Site Title
  description: A brief description of your site.
  url: "https://your-username.github.io"
  twitter: yourusername
  type: website

