# Site Settings
title: Lucas Czajka
baseurl: "" # Leave this empty for root domain deployment
url: "https://lucas-czajka.github.io/"

# Author Info
author:
  name: Lucas Czajka
  email: lucasczajka@berkeley.edu

# Theme and Plugins
theme: minima
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Navigation for Sections
nav_links:
  - title: "About Me"
    url: /about-me
  - title: "Projects"
    url: /projects
  - title: "Experience"
    url: /experience
  - title: "Contact"
    url: /contact

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# SEO Settings
seo:
  title: Your Site Title
  description: A brief description of your site.
  url: "https://your-username.github.io"
  twitter: yourusername
  type: website
